### ISSUE TITLE
Weird expand bug

### ISSUE THREAD

**Issue by Allazzanni** [GPKyte/MSOrderQueue#27]
when I first loaded the app, I hit expand before anything else and the 4 printers it had initialized were wiped. Not sure where they went, I tried putting more in and hitting expand again, but it did not wipe. It may be an issue with how the printers are initialized.

**Comment by GPKyte** [comment]
This was a well-time conflict with our dev database. We likely cleared out at the same time. The expand button is now merged into the job object itself and does not cause this issue
